brew "git"
brew "git-secret"
brew "git-lfs"
brew "doctl"
brew "nvm"
brew "gnupg"
brew "htop"
brew "neovim"
brew "the_silver_searcher"
brew "s3cmd"
brew "heroku"
brew "ghi"
brew "kubernetes-cli"
brew "imagemagick"
brew "libpq", link: true
brew "chrome-cli"
brew "go"
brew "mutt"
brew "hub"

tap "caskroom/fonts"
cask "font-fira-code"

tap "caskroom/cask"
cask "keybase"
cask "google-chrome"
cask "spotify"
cask "sublime-text"
cask "alfred"
cask "spectacle"
cask "flux"
cask "little-snitch"
cask "sublime-merge"
cask "sketch"
cask "dash"
cask "dropbox"
cask "docker"

tap "homebrew/cask-versions"
cask "iterm2-nightly"
