brew "bash"
brew "git"
brew "git-secret"
brew "tmux"
brew "doctl"
brew "nvm"
brew "gnupg"
brew "htop"
brew "neovim"
brew "the_silver_searcher"
brew "s3cmd"
brew "kubernetes-cli"
brew "imagemagick"
brew "libpq", link: true
brew "chrome-cli"
brew "go"
brew "python"

tap "caskroom/fonts"
cask "font-fira-code"

tap "caskroom/cask"
cask "keybase"
cask "google-chrome"
cask "spotify"
cask "alfred"
cask "spectacle"
cask "flux"
cask "little-snitch"
cask "dash"
cask "docker"
cask "1password"
cask "notion"

tap "homebrew/cask-versions"
cask "iterm2-nightly"
