#!/usr/bin/env bash

if [[ $PLATFORM == 'macos' ]]; then
  alias ls='ls -G'
  alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
  alias smerge='/Applications/Sublime\ Merge.app/Contents/SharedSupport/bin/smerge'
fi

if [[ $PLATFORM == 'linux' ]]; then
  alias ls='ls --color=auto'
fi

alias server='python -m SimpleHTTPServer'

# Edit shortcuts
alias e-bash="$EDITOR ~/.bash_profile"
alias e-gitconfig="$EDITOR ~/.gitconfig"
alias e-config="$EDITOR ~/.ssh/config"

# doctl shortcuts
alias dosh='doctl compute ssh'
alias dosh-root='doctl compute ssh --ssh-user root'
alias dcd='doctl compute droplet'

# Shortcuts
alias z='git lo'
alias x='git status'
alias c='git commit'
alias v='git diff'
alias d='cd ~/dotfiles'
alias s='cd ~/Desktop'
alias a='cd ~'

