#!/usr/bin/env bash

if [[ $PLATFORM == 'macos' ]]; then
  alias ls='ls -G'
fi

if [[ $PLATFORM == 'linux' ]]; then
  alias ls='ls --color=auto'
fi

# Launch silversearch with default ignore
alias ag='ag --path-to-ignore ~/.ignore'

# Shortcuts
alias z='git lo'
alias x='git status'
alias c='git commit'
alias C='git aa && git commit'
alias v='git diff'
alias b='git branch -rav'
alias s='cd ~/dev'
alias a='cd ~'

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# git
alias gc="git clone"

# docker
alias dps="docker ps"
alias dpa="docker ps -a"

# k8s
alias k='kubectl'
