#!/usr/bin/env bash

# Detect platform
PLATFORM='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   PLATFORM='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
   PLATFORM='macos'
fi
export $PLATFORM
 
# Fix for issue (Inappropriate ioctl for device): https://github.com/keybase/keybase-issues/issues/2798
export GPG_TTY=$(tty)

# Set default editor
EDITOR="vi"

if [ -x "$(command -v vim)" ]; then
  EDITOR="vim"
fi

if [ -x "$(command -v nvim)" ]; then
  EDITOR="nvim"
fi

export EDITOR

source "${DOTFILE_BASH_DIR}/vendor/git-completion.bash"
source "${DOTFILE_BASH_DIR}/vendor/iterm2_shell_integration.bash"

# Set nvm home directory
export NVM_DIR="$HOME/.nvm"

# Close only after C-d hit 10 times
export IGNOREEOF=10
