#!/usr/bin/env bash

if [[ $(id -u) -eq 0 ]]; then       # Root
  PS1="\[\e[2m\]\$(__git_ps1)\[\e[m\] $(jobscount)\[\e[31m\]\u\[\e[m\]@\[\e[34m\]\h\[\e[m\]:\W \[\e[90m\]$\[\e[m\] "
elif [[ -n "$SSH_CLIENT" ]]; then   # SSH session
  PS1="\[\e[2m\]\$(__git_ps1)\[\e[m\] $(jobscount)\[\e[32m\]\u\[\e[m\]@\[\e[34m\]\h\[\e[m\]:\W \[\e[90m\]$\[\e[m\] "
else                                # Normal
  PS1="\[\e[2m\]\$(__git_ps1)\[\e[m\] $(jobscount)\W \[\e[90m\]$\[\e[m\] "
fi
export PS1

